// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Task8_UnitTesting.Context;

#nullable disable

namespace Task8_UnitTesting.Migrations
{
    [DbContext(typeof(GadgetDbContext))]
    [Migration("20221006121843_l")]
    partial class l
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Task8_UnitTesting.Model.GadgetClass", b =>
                {
                    b.Property<int>("GadgetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GadgetId"), 1L, 1);

                    b.Property<string>("GadgetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GadgetPrice")
                        .HasColumnType("int");

                    b.Property<string>("GadgetType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GadgetId");

                    b.ToTable("GadgetTbl");
                });
#pragma warning restore 612, 618
        }
    }
}
